theme: jekyll-theme-tactile
title: Welcome to Malay Singh's homepage.
description: I am an Experimental Physicist, currently conducting my Ph.D studies in Quantum Computing with Superconducting Qubits at the Walther Meissner Institute for Low Temperature Research, TU Munich. 
